Fix __repr__ crash in Python 3
In Python >3.0, the following results in a TypeError:

    >>> import libmr
    >>> mr = libmr.MR()
    >>> print(mr)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      TypeError: __str__ returned non-string (type bytes)

This patch restores the expected behavior of converting to str.
Tested on Python 2.7.12 and 3.5.2.